AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  aws202001nhom1tomatoseslambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 5
      Role: 'arn:aws:iam::059456575734:role/aws2020-01-nhom1-tomato-ses-db-role'
      Events:
        DynamoDB1:
          Type: DynamoDB
          Properties:
            Stream:
              'Fn::GetAtt':
                - Table1
                - StreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize: 100
        DynamoDB2:
          Type: DynamoDB
          Properties:
            Stream:
              'Fn::GetAtt':
                - Table2
                - StreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize: 100
        DynamoDB3:
          Type: DynamoDB
          Properties:
            Stream:
              'Fn::GetAtt':
                - Table3
                - StreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize: 100
        DynamoDB4:
          Type: DynamoDB
          Properties:
            Stream:
              'Fn::GetAtt':
                - Table4
                - StreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize: 100
        DynamoDB5:
          Type: DynamoDB
          Properties:
            Stream:
              'Fn::GetAtt':
                - Table5
                - StreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize: 100
        DynamoDB6:
          Type: DynamoDB
          Properties:
            Stream:
              'Fn::GetAtt':
                - Table6
                - StreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize: 100
        DynamoDB7:
          Type: DynamoDB
          Properties:
            Stream:
              'Fn::GetAtt':
                - Table7
                - StreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize: 100
        DynamoDB8:
          Type: DynamoDB
          Properties:
            Stream:
              'Fn::GetAtt':
                - Table8
                - StreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize: 100
        DynamoDB9:
          Type: DynamoDB
          Properties:
            Stream:
              'Fn::GetAtt':
                - Table9
                - StreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize: 100
        DynamoDB10:
          Type: DynamoDB
          Properties:
            Stream:
              'Fn::GetAtt':
                - Table10
                - StreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize: 100
        DynamoDB11:
          Type: DynamoDB
          Properties:
            Stream:
              'Fn::GetAtt':
                - Table11
                - StreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize: 100
        DynamoDB12:
          Type: DynamoDB
          Properties:
            Stream:
              'Fn::GetAtt':
                - Table12
                - StreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize: 100
  Table1:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  Table2:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  Table3:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  Table4:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  Table5:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  Table6:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  Table7:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  Table8:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  Table9:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  Table10:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  Table11:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  Table12:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE
