AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  aws202001nhom1tomatogetshipInfoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: >-
        arn:aws:iam::059456575734:role/service-role/aws2020-01-nhom1-tomato-shipInfo-Lambda-role-mid87vg4
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /shipinfo
            Method: GET
        Api2:
          Type: Api
          Properties:
            Path: /getinfo
            Method: POST
